### Sign In
POST http://localhost:3000/v1/auth/sign-in
Content-Type: application/json

{
    "nik": "1234123412341233",
    "password": "Password123!@#"
}

# Response:
# {
#   "access_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...",
#   "refresh_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
# }

### Sign Up
POST http://localhost:3000/v1/auth/sign-up
Content-Type: application/json

{
    "nik": "1234123412341233",
    "full_name": "John Doe",
    "legal_name": "Johnathan Doe",
    "date_of_birth": "1990-01-01",
    "place_of_birth": "Cityville",
    "salary": 50000000,
    "id_card_photo_url": "http://example.com/id_card.jpg",
    "selfie_photo_url": "http://example.com/selfie.jpg",
    "password": "Password123!@#"
}

### Find User by ID
GET http://localhost:3000/v1/user/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAxSlpBMDlRSlZGUDg3WVg5Vk45NEM1WEdaIiwiaXNfYWRtaW4iOmZhbHNlLCJleHAiOjE3NTQyMDA3OTMsImlhdCI6MTc1MTYwODc5M30.3kohJqFI4-LIOKMx0_arxJL2vW35FuU7w2ER0uaSIuY


### Find User Limits
GET http://localhost:3000/v1/user/limit
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAxSlpBMDlRSlZGUDg3WVg5Vk45NEM1WEdaIiwiaXNfYWRtaW4iOmZhbHNlLCJleHAiOjE3NTQyMDA3OTMsImlhdCI6MTc1MTYwODc5M30.3kohJqFI4-LIOKMx0_arxJL2vW35FuU7w2ER0uaSIuY

### Find Partners
GET http://localhost:3000/v1/partner
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAxSlo4RDhXQ1RIN05FS1dNRVRWSkdUQUZFIiwiaXNfYWRtaW4iOmZhbHNlLCJleHAiOjE3NTQxNTY0NjgsImlhdCI6MTc1MTU2NDQ2OH0.5WliJGP3JRNN6mv0KnghgqRH7_FkUoLws6jw3TELgzI

### Create Partner
POST http://localhost:3000/v1/partner
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAxSlo4RDhXQ1RIN05FS1dNRVRWSkdUQUZFIiwiaXNfYWRtaW4iOmZhbHNlLCJleHAiOjE3NTQxNTY0NjgsImlhdCI6MTc1MTU2NDQ2OH0.5WliJGP3JRNN6mv0KnghgqRH7_FkUoLws6jw3TELgzI

{
    "name": "Dealer 1",
    "type": "dealer"
}

### Find Assets
GET http://localhost:3000/v1/asset
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAxSlo4RDhXQ1RIN05FS1dNRVRWSkdUQUZFIiwiaXNfYWRtaW4iOmZhbHNlLCJleHAiOjE3NTQxNTY0NjgsImlhdCI6MTc1MTU2NDQ2OH0.5WliJGP3JRNN6mv0KnghgqRH7_FkUoLws6jw3TELgzI

### Create Asset
POST http://localhost:3000/v1/asset
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAxSlo4NkRCWTZOWFJaUTNYSEU0WEJONUNYIiwiaXNfYWRtaW4iOnRydWUsImV4cCI6MTc1NDE1OTIzNSwiaWF0IjoxNzUxNTY3MjM1fQ.yHB-FgFrxuGKoyRDn7szi_k5bklOfVCvVT9aRNSwYt8

{
    "name": "Asset Dealer 1",
    "price": 10000000,
    "partner_id": "01JZ8P0BE7KPHGD2WV8GAP6K1W"
}

### Find Transactions
GET http://localhost:3000/v1/transaction
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAxSlpBMDlRSlZGUDg3WVg5Vk45NEM1WEdaIiwiaXNfYWRtaW4iOmZhbHNlLCJleHAiOjE3NTQyMDA3OTMsImlhdCI6MTc1MTYwODc5M30.3kohJqFI4-LIOKMx0_arxJL2vW35FuU7w2ER0uaSIuY

### Create Transaction
POST http://localhost:3000/v1/transaction
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjAxSlpBMDlRSlZGUDg3WVg5Vk45NEM1WEdaIiwiaXNfYWRtaW4iOmZhbHNlLCJleHAiOjE3NTQyMDA3OTMsImlhdCI6MTc1MTYwODc5M30.3kohJqFI4-LIOKMx0_arxJL2vW35FuU7w2ER0uaSIuY

{
    "asset_id": "01JZ8RVRJED217DYYNH07H14JF",
    "tenor": 1
}